// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarBrandsController from "./car_brands_controller"
application.register("car-brands", CarBrandsController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import VehicleInfoController from "./vehicle_info_controller"
application.register("vehicle-info", VehicleInfoController)
