// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ListingWizardController from "./listing_wizard_controller"
application.register("listing-wizard", ListingWizardController)

import PhotoDropzoneController from "./photo_dropzone_controller"
application.register("photo-dropzone", PhotoDropzoneController)

import RustMapEditorController from "./rust_map_editor_controller"
application.register("rust-map-editor", RustMapEditorController)

import ProvenanceTimelineController from "./provenance_timeline_controller"
application.register("provenance-timeline", ProvenanceTimelineController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PhotoLightboxController from "./photo_lightbox_controller"
application.register("photo-lightbox", PhotoLightboxController)

import AuctionController from "./auction_controller"
application.register("auction", AuctionController)
