// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)
